from collections import defaultdict
import pprint
pp = pprint.PrettyPrinter()

sTable = defaultdict(lambda : defaultdict(dict))

sTable['int']['int']['and'] = 'bool'
sTable['int']['int']['or'] = 'bool'
sTable['int']['int']['>'] = 'bool'
sTable['int']['int']['<'] = 'bool'
sTable['int']['int']['<>'] = 'bool'
sTable['int']['int']['=='] = 'bool'
sTable['int']['int']['<='] = 'bool'
sTable['int']['int']['>='] = 'bool'
sTable['int']['int']['+'] = 'int'
sTable['int']['int']['-'] = 'int'
sTable['int']['int']['*'] = 'int'
sTable['int']['int']['/'] = 'int'
sTable['int']['int']['='] = 'int'

sTable['float']['float']['and'] = 'bool'
sTable['float']['float']['or'] = 'bool'
sTable['float']['float']['>'] = 'bool'
sTable['float']['float']['<'] = 'bool'
sTable['float']['float']['<>'] = 'bool'
sTable['float']['float']['=='] = 'bool'
sTable['float']['float']['<='] = 'bool'
sTable['float']['float']['>='] = 'bool'
sTable['float']['float']['+'] = 'float'
sTable['float']['float']['-'] = 'float'
sTable['float']['float']['*'] = 'float'
sTable['float']['float']['/'] = 'float'
sTable['float']['float']['='] = 'float'

sTable['char']['char']['and'] = 'bool'
sTable['char']['char']['or'] = 'bool'
sTable['char']['char']['>'] = 'bool'
sTable['char']['char']['<'] = 'bool'
sTable['char']['char']['<>'] = 'bool'
sTable['char']['char']['=='] = 'bool'
sTable['char']['char']['>='] = 'bool'
sTable['char']['char']['<='] = 'bool'
sTable['char']['char']['+'] = 'char'
sTable['char']['char']['-'] = 'char'
sTable['char']['char']['*'] = 'char'
sTable['char']['char']['/'] = 'char'
sTable['char']['char']['='] = 'char'

sTable['bool']['bool']['and'] = 'bool'
sTable['bool']['bool']['or'] = 'bool' 
sTable['bool']['bool']['>'] = 'bool' 
sTable['bool']['bool']['<'] = 'bool' 
sTable['bool']['bool']['<>'] = 'bool'  
sTable['bool']['bool']['=='] = 'bool' 
sTable['bool']['bool']['>='] = 'bool'
sTable['bool']['bool']['<='] = 'bool' 
sTable['bool']['bool']['+'] = 'int'
sTable['bool']['bool']['-'] = 'int'
sTable['bool']['bool']['*'] = 'int' 
sTable['bool']['bool']['/'] = 'int' 
sTable['bool']['bool']['='] = 'int'

sTable['int']['float']['and'] = sTable['float']['int']['and'] = 'bool'
sTable['int']['float']['or'] = sTable['float']['int']['or'] = 'bool'
sTable['int']['float']['>'] = sTable['float']['int']['>'] = 'bool'
sTable['int']['float']['<'] = sTable['float']['int']['<'] = 'bool'
sTable['int']['float']['<>'] = sTable['float']['int']['<>'] = 'bool'
sTable['int']['float']['=='] = sTable['float']['int']['=='] = 'bool'
sTable['int']['float']['<='] = sTable['float']['int']['<='] = 'bool'
sTable['int']['float']['>='] = sTable['float']['int']['>='] = 'bool'
sTable['int']['float']['+'] = sTable['float']['int']['+'] = 'float'
sTable['int']['float']['-'] = sTable['float']['int']['-'] = 'float'
sTable['int']['float']['*'] = sTable['float']['int']['*'] = 'float'
sTable['int']['float']['/'] = sTable['float']['int']['/'] = 'float'
sTable['int']['float']['='] = sTable['float']['int']['='] = 'float'

sTable['int']['char']['and'] = sTable['char']['int']['and'] = 'char'
sTable['int']['char']['or'] = sTable['char']['int']['or'] = 'char'
sTable['int']['char']['>'] = sTable['char']['int']['>'] = 'char'
sTable['int']['char']['<'] = sTable['char']['int']['<'] = 'char'
sTable['int']['char']['<>'] = sTable['char']['int']['<>'] = 'char'
sTable['int']['char']['=='] = sTable['char']['int']['=='] = 'char'
sTable['int']['char']['<='] = sTable['char']['int']['<='] = 'char'
sTable['int']['char']['>='] = sTable['char']['int']['>='] = 'char'
sTable['int']['char']['+'] = sTable['char']['int']['+'] = 'char'
sTable['int']['char']['-'] = sTable['char']['int']['-'] = 'char'
sTable['int']['char']['*'] = sTable['char']['int']['*'] = 'char'
sTable['int']['char']['/'] = sTable['char']['int']['/'] = 'char'
sTable['int']['char']['='] = sTable['char']['int']['='] = 'char'

sTable['int']['bool']['and'] = sTable['bool']['int']['and'] = 'bool'
sTable['int']['bool']['or'] = sTable['bool']['int']['or'] = 'bool'
sTable['int']['bool']['>'] = sTable['bool']['int']['>'] = 'bool'
sTable['int']['bool']['<'] = sTable['bool']['int']['<'] = 'bool'
sTable['int']['bool']['<>'] = sTable['bool']['int']['<>'] = 'bool'
sTable['int']['bool']['=='] = sTable['bool']['int']['=='] = 'bool'
sTable['int']['bool']['<='] = sTable['bool']['int']['<='] = 'bool'
sTable['int']['bool']['>='] = sTable['bool']['int']['>='] = 'bool'
sTable['int']['bool']['+'] = sTable['bool']['int']['+'] = 'int'
sTable['int']['bool']['-'] = sTable['bool']['int']['-'] = 'int'
sTable['int']['bool']['*'] = sTable['bool']['int']['*'] = 'int'
sTable['int']['bool']['/'] = sTable['bool']['int']['/'] = 'int'
sTable['int']['bool']['='] = sTable['bool']['int']['='] = 'int'

sTable['float']['char']['and'] = sTable['char']['float']['and'] = 'bool'
sTable['float']['char']['or'] = sTable['char']['float']['or'] = 'bool'
sTable['float']['char']['>'] = sTable['char']['float']['>'] = 'bool'
sTable['float']['char']['<'] = sTable['char']['float']['<'] = 'bool'
sTable['float']['char']['<>'] = sTable['char']['float']['<>'] = 'bool'
sTable['float']['char']['=='] = sTable['char']['float']['=='] = 'bool'
sTable['float']['char']['<='] = sTable['char']['float']['<='] = 'bool'
sTable['float']['char']['>='] = sTable['char']['float']['>='] = 'bool'
sTable['float']['char']['+'] = sTable['char']['float']['+'] = 'float'
sTable['float']['char']['-'] = sTable['char']['float']['-'] = 'float'
sTable['float']['char']['*'] = sTable['char']['float']['*'] = 'float'
sTable['float']['char']['/'] = sTable['char']['float']['/'] = 'float'
sTable['float']['char']['='] = sTable['char']['float']['='] = 'float'

sTable['float']['bool']['and'] = sTable['bool']['float']['and'] = 'bool'
sTable['float']['bool']['or'] = sTable['bool']['float']['or'] = 'bool'
sTable['float']['bool']['>'] = sTable['bool']['float']['>'] = 'bool'
sTable['float']['bool']['<'] = sTable['bool']['float']['<'] = 'bool'
sTable['float']['bool']['<>'] = sTable['bool']['float']['<>'] = 'bool'
sTable['float']['bool']['=='] = sTable['bool']['float']['=='] = 'bool'
sTable['float']['bool']['<='] = sTable['bool']['float']['<='] = 'bool'
sTable['float']['bool']['>='] = sTable['bool']['float']['>='] = 'bool'
sTable['float']['bool']['+'] = sTable['bool']['float']['+'] = 'float'
sTable['float']['bool']['-'] = sTable['bool']['float']['-'] = 'float'
sTable['float']['bool']['*'] = sTable['bool']['float']['*'] = 'float'
sTable['float']['bool']['/'] = sTable['bool']['float']['/'] = 'float'
sTable['float']['bool']['='] = sTable['bool']['float']['='] = 'float'

sTable['char']['bool']['and'] = sTable['bool']['char']['and'] = 'bool'
sTable['char']['bool']['or'] = sTable['bool']['char']['or'] = 'bool'
sTable['char']['bool']['>'] = sTable['bool']['char']['>'] = 'bool'
sTable['char']['bool']['<'] = sTable['bool']['char']['<'] = 'bool'
sTable['char']['bool']['<>'] = sTable['bool']['char']['<>'] = 'bool'
sTable['char']['bool']['=='] = sTable['bool']['char']['=='] = 'bool'
sTable['char']['bool']['<='] = sTable['bool']['char']['<='] = 'bool'
sTable['char']['bool']['>='] = sTable['bool']['char']['>='] = 'bool'
sTable['char']['bool']['+'] = sTable['bool']['char']['+'] = 'char'
sTable['char']['bool']['-'] = sTable['bool']['char']['-'] = 'char'
sTable['char']['bool']['*'] = sTable['bool']['char']['*'] = 'char'
sTable['char']['bool']['/'] = sTable['bool']['char']['/'] = 'char'
sTable['char']['bool']['='] = sTable['bool']['char']['='] = 'char'

sTable['int']['float'][''] = sTable['float']['int'][''] = 'float'


pp.pprint(sTable)