block_size = 1_000
types_amount = 5
data_lower_limit = 1_000
data_upper_limit = data_lower_limit + block_size * types_amount
instance_lower_limit = 6_000
instance_upper_limit = instance_lower_limit + block_size * types_amount
procedure_lower_limit = 11_000
procedure_upper_limit = procedure_lower_limit + block_size  * types_amount
cte_lower_limit = 16_000
cte_upper_limit = cte_lower_limit + block_size * 5
int_lower_limit = 0
int_upper_limit = int_lower_limit + block_size
float_lower_limit = int_upper_limit + 1
float_upper_limit = float_lower_limit + block_size
char_lower_limit = float_upper_limit + 1
char_upper_limit = char_lower_limit + block_size
bool_lower_limit = char_upper_limit + 1
bool_upper_limit = bool_lower_limit + block_size
class_lower_limit = bool_upper_limit + 1
class_upper_limit = class_lower_limit + block_size
